import type { RadialSliderDebugTouchConfig } from './types';
import { Colors } from '../../theme';

export const defaultProps = {
  radius: 100,
  min: 0,
  max: 100,
  step: 1,
  value: 0,
  title: '',
  subTitle: 'Goal',
  unit: '',
  thumbRadius: 18,
  thumbColor: Colors.blue,
  thumbBorderWidth: 5,
  thumbBorderColor: Colors.white,
  markerLineSize: 50,
  sliderWidth: 18,
  unselectedSliderWidth: 18,
  sliderTrackColor: Colors.grey,
  lineColor: Colors.grey,
  lineSpace: 3,
  lineTrackGap: 0,
  linearGradient: [
    { offset: '0%', color: Colors.skyBlue },
    { offset: '100%', color: Colors.darkBlue },
  ],
  onChange: (_v: number) => {},
  onComplete: (_v: number) => {},
  openingRadian: Math.PI / 3,
  disabled: false,
  isHideSlider: false,
  isHideThumb: false,
  isHideTitle: false,
  isHideSubtitle: false,
  isHideValue: false,
  isHideTailText: false,
  isHideButtons: false,
  isHideLines: false,
  isHideMarkerLine: false,
  isHideCenterContent: false,
  fixedMarker: false,
  variant: 'default',
  markerValueInterval: 10,
  debugTouch: false as RadialSliderDebugTouchConfig,
};
